import React, { Component } from "react";
import "../styles/global.css";

export default class AAEssay extends Component {
  render(){
    return(
      <div>
        <p>
          A Thin Line: Asian-American Success in Creative Industries <br/>
          <i>By Bowen Chen</i>
        </p>

        <p>
        What many people may not remember is that aboard the space shuttle Challenger on that fateful morning was Astronaut Ellison Onizuka, the first Asian American to reach space. For most Americans, the crew of the Challenger were American heroes. For my parents, however, Ellison wasn’t an aerospace pioneer, simply a warning to the dangers of chasing your dreams as another expendable Asian American in a white world.
        <br/>&emsp;&emsp;
        At some point in elementary school, around second or third grade I can’t precisely recall, my teacher asked us what we wanted to be when we grew up. When you’re seven years old, you aren't able to name that many careers, only what you see on television or read in picture books. A lot of kids answered with policeman, firefighter, teacher, astronaut. I don’t remember what I said. Back then, I didn’t know what I wanted to be, I only knew what I didn’t want to be – a doctor. At the age of seven, I was already being trained by my parents in the complex field of risk assessment, and more specifically, risk aversion.
        <br/>&emsp;&emsp;

        For many Chinese-Americans who have grown up in the states, raised by  first-generation immigrant parents, our lives have always centered around the promise of stability. For them their escape from uncertainty meant a proceeding generation paired with the guaranteed likelihood of success, which in their eyes were a series of rings to hop through, items on a bucket list that you checked off one at a time: perfect A’s, ace your SAT, ivy league university, MCATs, residency. To them, becoming a doctor was the ideal job, you spent years of your life climbing rings on a ladder, and then you reap your rewards of guaranteed employment with a six-figure salary. The steps were laid out to you, clear as day. It was all so simple. When I told my dad I was going to study the ever-so-risky profession of Computer Science, he had exclaimed, “Oh that’s not a good job, not a good job at all. The job market is too unstable for computer scientists, you can’t do that for life.” He was referring towards the dot.com crash that had sent many of his colleagues studying the field, to America in search of employment.
        <br/>&emsp;&emsp;

        In the professional world however, success is not so cut in stone like the path to becoming a doctor. Asian-American’s often find it difficult to rise in the ranks of the corporate world, unable to reach comfortable positions of smiling, handshaking, closing multi-million-dollar deals in glass pent-houses. Despite being trained for success, we have often fallen short. In 2005, Jenny Heung coined the term ‘the bamboo ceiling’ referring to this specific phenomenon. In his 2008 essay, “Paper Tigers”, Wesley Yang talks about this in depth, the external pressure to assimilate in order to succeed the predominately white corporate world. This pressure is similarly offset by the heightened awareness of our identity and the pressure to create work surrounding it in the humanities and creative arts. In its overtly zealous manner in which is ‘encourages’ inclusivity, many ethnic writers have become commercialized, commodified, fetishized, without even realizing it. It is important to remember, that like the corporate world, the art world is also predominantly white and controlled by similar players, yet cognizant of its racial disparities, so it lauds ethnic writers in attempt at self-gratification.
        <br/>&emsp;&emsp;

        In this day and age, often it is no longer about what we write as authors, but the face behind the writing. Author’s must make sure to carefully align their marginalized characters with their own marginalized identities, or risk being caught in the midst of a Twitterstorm of cancel culture. I am not arguing that this is a bad thing, on the contrary I believe that, when moved away from its extremities, a readership that upholds ethical writing helps draw attention to underrepresented writers whose work more closely draws upon intimate lived experiences. The problem arises, however, when writers use their faces, their skin, as a ‘free pass’ token to create work that is leagues beyond the spectrum of their lived experiences. If I, a second-generation Asian-American were to write an imitation piece trying to be distinctly Chinese, would the online media mob stand to correct me, or quickly pass over my name and the shape of my face and treat them as an undeniable birthright?

        </p>
        <p style ={{textAlign:"center"}}> +++ </p>
        <p>
        In 2014, Rupi Kaur published her debut book, a collection of flash poems titled milk and honey. It stayed on the New York Times Bestseller list for over a year and to date, has sold over 2.5 million print copies. Kaur, the most prominent presence behind a rising wave of instapoets, is perhaps also one of the most visible female South-Asian voices in the digital world of contemporary media. Kaur, whose poetry revolves around personal experiences of trauma, femme-narratives, and the South Asian female body, champions transparency for female experiences, especially those regarding trauma. In 2013, she garnered mass media attention when she criticized Instagram for twice deleting a post of her lying in bed with her pants and sheets covered in period blood. The photo was part of a project of Kaur’s that aimed to demystify the taboos surrounding menstruation. In the FAQ section of her website, Kaur responds that her project milk and honey takes from “a lot of pain I’ve experienced or my family has experienced. Or my community has experienced. Or the South Asian community and diaspora”.
        <br/>&emsp;&emsp;

        In her interview with Playground + , when asked “Why is it so important to tell stories from your culture as a South Asian women”, Kaur says “I can only speak about my lived experience and of the women around me – my mother, the life she’s lived , her mother, my sisters and so on.” In her mission to represent the entirety of South Asian women, Kaur has fallen prey to the ‘uneasy postmodern trend towards collapsing diasporic differences in the postcolonial literature they produce’ as noted by Chiara Giovanni in her Buzzfeed article, originally from Vijay Mishra’s book The Literature of the Indian Diaspora: Theorizing the Diasporic Imaginary. Kaur fails to acknowledge the intricacies behind the diversity behind the lived experiences of South Asians, and even falls short of separating her own identity as a privileged, western-educated Punjabi-Sikh Canadian woman from the South Asian women she claims to champion, whose lived experience differs from hers like night and day.
        <br/>&emsp;&emsp;

        It is easy to see how Kaur’s poetry is voraciously consumed by white femme millennials across the (western) world. Aside from the simplicity of her poetry, which Kaur openly admits to as stylistic choice, it is gratifying for white readers to feel like their consumption of Kaur’s poetry is serving to broaden their cultural knowledge or help them become more ‘ethnically woke’. In her interview with CBS news, Kaur claims that when her debut book was published, all she wanted was her last name, common among Sikh women, on the cover. In congruence with how Kaur advocates herself as a writer representative of Punjabi-Sikh women, it is easy to see how white audiences retreat to the proximity of her poetry rather than educate themselves with the wide range of South Asian literature.
        <br/>&emsp;&emsp;


        When an author’s writing begins to connect with white, teenage, suburban girls more than the community she claims to represent, there arises a deeply unsettling feeling. What started out as well-meaning work shared amongst Pakistani family & friends had quickly become appropriated by the white masses. Is mass publicity necessarily a bad thing? In short, no. I do, however, think that as writers we need to be careful about the avenues through which our work travels, to how it is reaching our audiences and how they are led to perceive it.
        </p>
        <p style ={{textAlign:"center"}}> +++ </p>
        <p>
        I would like to draw attention to another project that I believe falls prey to creative self-righteousness. Alexandra Leese, a photographer who has shot campaigns and editorials for Helmut Lang, ID, and Self Service Mag, and her most recent project, ‘Boys of Hong Kong’, a collection of portraits of young, male, Hong Kong natives. Leese, who is Chinese British, moved to London from her Hong Kong hometown when she was 11, and briefly returned to Hong Kong for this most recent project, which she talks about in her interview with Office Mag, titled ‘Alex Leese Goes Home’.
        <br/>&emsp;&emsp;

        The article’s subline remarks about Leese, ‘After moving to London, Leese’s innate fondness for Hong Kong and its culture became tainted by Western Prejudice. However, Boys of Hong Kong is her act of rebellion, and allows her to rise above her learned prejudice.” This is immediately followed by Leese’s comments on how her work addresses the emasculation of Asian men. When asked about her goals for this project, Leese responds,“I wanted to show the world how beautiful Asian men are, and to celebrate this! Quite often, in the West, Asian men are not seen as attractive. I wanted to counter this prejudice by creating and showing a set of portraits that celebrates an incredible range of masculine beauty, from my amazing hometown.”
        </p>
        <p>

        It is true that Western media has a history of portraying Asian men as docile, subhuman, and undesirable, but Leese’s comments go to show an ignorance in the twisted narratives she ties her subjects into. In her efforts to ‘rise above her learned prejudice’, she has gone and invaded the youth culture in a disconnected city and portrayed its subjects in an attempt to conform them to western beauty standards. These portraits have been explicitly framed in a western lens, published in western magazines (i-D, Vice), displayed in western galleries (London’s Red Gallery), for primarily western audiences. I am unable to see how this is an attempt to rectify western notions of desirability when it clearly is another eye-candy exhibition of Orientalism.
        <br/>&emsp;&emsp;

        While the color of your skin may be indicative of your lived experiences, it does not give you a free-pass token to attention-grab when there are more deserving artists. Leese’s portraiture of the male youth in Hong Kong is at most a recreation of other Hong Kong and Chinese photographers such as Liu Wen(@liuwenlw), Wingla Wong (@_vcrs), and Lee Ann Lui (@leanlui), who lived their lives surrounded by Hong Kong and Chinese youth culture, and did not simply ‘return home without a solid plan and explored’ as Leese admitted to doing. This is not the first time Leese’s projects have revolved around Hong Kong residents. In a previous portraiture project titled Hong Kong Taxi Drivers, Leese set out to photograph a group that she was even further disconnected from than her subjects in Boys of Hong Kong.
        </p>
        <p style ={{textAlign:"center"}}> +++ </p>
        <p>
        In Leese’s case, we find an instance of a creative pushed to produce work that will be readily accepted by a Western fanbase. This audience pressure is present for all Asian-American, British-Asian, Asian-Canadian creatives. A famous example can be found within the works and interviews with Kazuo Ishiguro, the Japanese author who was raised in the UK and awarded the Nobel Prize in Literature in 2017. Ishiguro’s debut novel, A Pale View of Hills, follows the murky history of a mother raising her daughter in Japan, but what many readers don’t know is that the novel was first set in Cornwall, and it was only upon the feedback of his classmates that Ishiguro decided the parochial setting would resonate more in Japan. Ishiguro has done an excellent job of explicitly stating his stance on his own identity as a British author, not Japanese or British-Japanese, but a British author who occasionally draws a slight thematic from his childhood and summers spent in Japan. However, despite this firm stance, the public relentlessly pursuits his Japanese origins. In an interview with Electric Lit, Elysha Chang remarks about his most recent novel, the Buried Giant, “I love the way there’s still something Japanese that comes across in its style and tone.” For context, the Buried Giant, follows an elderly couple set in a medieval England fantasy landscape. No matter how far detached Ishiguro’s novels stray from his Japanese roots, his irreversible characters in his name and the never-ending stream of readers who to him, attribute their love of contemporary Japanese, will continue to haunt him for the foreseeable future.
        <br/>&emsp;&emsp;

        As Asian-American writers, photographers, creatives, and I am specifically referring to a subset of Asian-American, those of us who have grown up our entire lives in a Western country, educated by Western ideals, we need to do better, hold ourselves to a higher standard. It is cheap of us to simply escape to our ‘home’ countries and create projects where we ‘rediscover it with fresh eyes’. Our lived experience like each individual on this planet is undeniably unique and provides us with more than enough content to express ourselves for. When we reduce our work to an attempt to ‘reconnect’ with a disconnected ancestry, it calls for a momentary distancing to think about the lens in which we and our audience perceives our work. If it is an introspective reflection on ourselves, a journey to genuinely reconnect, that reflect that sense of yearning and displacement, then we must find a way to convey it. But if we find that our project is misrepresenting a culture we know despairingly little about and we, another stranger with a camera or a pen profiting off western dreams of orientalism, then we need to do better.
        </p>
      </div>
    );
  }
}
