import React, { Component } from "react";
import FrancescaWoodman from "../images/woodman.jpg"
import "../styles/global.css";

export default class photoEssay extends Component {
  render(){
    return(
      <div>
        <p>
          Escaping the Frame: Looking Beyond the Photographs of Francesca Woodman <br/>
          <i>By Bowen Chen</i>
        </p>
        <p>
          The first time I was shown pictures of Francesca Woodman (taken by Francesca Woodman), I was sitting in the backseat of an Uber with my studio manager, a young Polish woman, holding a bronze-cast statue of my boss’s Border Collie. It was his wedding anniversary that weekend, and I had spent the entire morning running a daisy chain of errands from forge to studio to Whole Foods and back again. One metal sculptor had made me ride on his invention (patented), a scooter-skateboard hybrid equipped with a 100cc combustion engine.<br/>
          &emsp;&emsp; I was working for a fashion photographer in Los Angeles who had risen to prominence in the early 2000s. In the mornings I would either be in his retouching studio mounting prints for Harper’s Bazaar and Gucci, or in the backseat of an Uber running errands between Hollywood and Santa Monica. Some afternoons, after eating lunch at the Whole Foods next to Venice Beach, I’d head to the large shed in my boss’s backyard where I archived old negatives of weddings and Prada campaigns. On the weekends, I would spend  my meager intern’s salary at different museums, seeking enlightenment from prints of the photographs they teach in art school. I remember my first week in the city, taking the bus downtown to the Museum of Contemporary Art to view Diane Arbus’s <i>identical twins, Roselle, New Jersey, 1967</i>. In the gift shop, I purchased <i>The Photographer’s Playbook</i>, a compendium of stories, tips, and exercises from over a hundred industry photographers. Since there existed great photographs, there existed attributes that made a photograph great. And while I didn’t necessarily want industry success, it was easy to tie it to greatness, and that was what I wanted more than anything—the ability to discern what made a photograph ‘great’.
        </p>

        <p>
          I don’t know what first attracted me to shooting film. Perhaps it was the Larry Clark x Supreme collab or the same reason alt-teens arrive at college with a Fjallraven backpack. I quickly became more interested in combing through the rare scraps of PDF photo books available online than taking photos. Like an athlete practicing for a match, I became obsessed with training my eye before tackling the camera. By the time I arrived in LA, I had taken no more than five rolls. I felt that my photos carried no intent, made no effort to reckon with the world as I saw it. Any pleasure I gained from my camera was dampened by the similarity I found between my work and that which dominated photography contests for amateurs. I enjoyed capturing products of industrialism fallen into decrepitude, such as office chairs with scuffed upholstery and broken-down trucks. Something about the materiality of analog film lends itself to reflective nostalgia. Once there is a base cost of producing a photograph— film, scanning, development, printing—there is suddenly a stake to releasing the shutter. The photographer falls prey to the misconception that each photograph must be extraordinary, which is at odds with how banal we perceive our surroundings, and the instinct is to run away from the familiar and towards the unknown. <br/>
          &emsp;&emsp;That summer, the Getty opened a new exhibit, <i>Icons of Style: A Century of Fashion Photography</i>, housed next to a rotating selection of famous prints from their archives. Included was a photograph taken by my boss of Kate Moss standing in Times Square, her fist blurred in front of the lens. He would tell me stories about living with Mario Sorrenti in his twenties, going to the darkroom in the city, and making color proofs next to Robert Frank. A print from <i>the Americans</i> hung on his wall, adorned in the kind of simple frame friends gift one another. I hungered for these stories of past interactions, believing that within them I could glean some thread of achievement or a lesson to be learned. I chose to spend a lot of afternoons in my boss’s shed, unpacking boxes of expensive photo books sheathed in plastic dust covers. They helped me develop a sense of what I would come to consider the American gold standard in portraiture—Walker Evans, Richard Avedon, Diane Arbus. In their portraits, there seemed to be an unspoken dialogue between the subject and the spectator, a compromised understanding behind the scene. When his subjects stood in front of the stark white backdrop of his studio, Avedon would not look through the ground glass of his Deardorff large format camera, but instead converse with and instruct them, pressing the shutter release cable when he thought their image was ready to be revealed to the world. In his book, In the American West, each photo stares back at me with variations of the same unyielding gaze. <br/>
          &emsp;&emsp;In the <i>Photographer’s Playbook</i>, an entry by Shelby Lee Adams suggests asking your subject to find their reflection within the lens. <i>In that singular moment, people are less focused on projecting an image of themselves for the camera and are more looking to find themselves</i>. There are several entries like his, exercises to coax your subject to drop their guard in order to capture the moment they are most at ease. Avedon’s subjects do not look comfortable or at ease. Instead, I would describe them as present. Sitting at the bar of an oyster shack (rare, as he was often away in Milan that summer), my boss told me, <i>it isn’t enough to lead someone to the perfect photograph, you have to teach them to make that choice themselves</i>. Photographers are preoccupied with the idea of a ‘candid’ photograph. It is an impossible task when taking a portrait. If you choose to ignore the camera’s presence, it will balloon until it fills the room.  I wonder how long it took Avedon to manufacture his conversational trick labyrinth, to have each subject ready to defy the passage of time with a look that said, here, look at me as I am now.<br/>
          &emsp;&emsp;On the weekends, I would take the bus around Los Angeles, riding not under the pretense of transportation, but for the intervals when the city’s ranks would gather around the glass booths. I told myself at each bus stop I would interact with one person, take one portrait, but it felt like I had fallen into the role of an unwilling anthropologist. Each moment felt contrived, each photograph stripped of authenticity. Every time I looked past my viewfinder I was gripped by guilt, afraid I was becoming a class voyeur. I was persistently unsuccessful, and by the end of the summer, I had accumulated leaflets of contact sheets filled with empty bus stops, the recently departed.
        </p>

        <p>
          I first viewed Woodman’s photographs with the understanding that her work has influenced a generation of fashion photographers, and that she took her own life at age 22. Her work has been published extensively in several collections and anthologies, and select prints will sell upwards of $100,000. Her death has been described as ‘untimely’ (most young people’s suicides are) and her photos ‘haunting’. The following year, I had the privilege of viewing the Rhode Island School of Design’s archive of Woodman’s past correspondences. There, I found a reliquary, home for her letters to Wendy MacNeil (her professor at the time), postcard-sized prints taped to A4 paper with masking tape. Some had been written during her time abroad in Italy, others following her graduation from RISD. The Manila envelopes she had used to send her work were discolored and had faded into a shade of muddy lavender and mustard. Each envelope had the same picture taped to its center, a portrait of Woodman. Her raven hair is tied in a bun. She is wearing a high collar lace dress. In a flowing ballpoint script, the words <i>please send pictures back to Francesca Woodman 33 2nd Ave. NY </i>floated above her. The material was collected post-mortem—she had no reason to believe they would be seen outside of their initial confidentiality.
        </p>

        <p>
          What is a photograph? I felt like I had missed the point. In technical terms, it is the result of a long lineage of techniques, originating with Niepce’s heliograph nearly two centuries ago (though Daguerre is given most of the credit). Modern-day film negatives are coated in silver halide emulsions that, when washed away, leave only the chemical imprint engraved by waves of light. Once the negative has been scanned and inverted, or a positive print has been made, the resulting photograph can be viewed from infinite angles. A modern-day image processing algorithm would analyze each pixel (in grid-like batches) to detect edges and features, running probability distributions that determine the likelihood of a matching object or face existing in the shot. Unlike a computer, the human experience of looking at a photograph goes beyond our visual experience—we don’t simply acknowledge what exists within the frame, but rather make cognitive connections between what we see in the photograph and our memories, daily experiences, what we see in the news and other media.<br/>
          &emsp;&emsp;In his essay "Appearances", John Berger writes how in photography, unlike any other creative medium, <i>the photographer only makes, in any one photograph, a single constitutive choice: the choice of the instant to be photographed</i>. And while this might undermine the infinitude of other choices made in tandem (the lighting, the composition, etc.), the only synaptic response directly attributing to the resultant photograph is the firing of the motor neurons, those responsible for movement of the index finger to release to the shutter. Because the photograph is an imprint in time, it carries inherent ambiguity and will deceive whether or not it intends to (as each viewing is based on a cognitive framework unique to the spectator). The photograph is a discontinuity taken from the continuum, blind to the events that precede and supersede its creation—it is what the spectator makes it to be, which is why the photograph lends itself so quickly to projection.<br/>
          &emsp;&emsp;In a review by <i>The Guardian</i>, Sean O’Hagan describes Woodman as <i>Alice about to disappear through the looking glass.</i> I have always been uncomfortable with how quick the media and critics are to venerate Woodman with the pre-Raphaelite adoration reserved for white-laced martyrs and saints. It reminds me too much of Ophelia and the Lisbon girls, of Sylvia Plath, how Woodman’s photographs have served as vessels to inhabit the standing culture’s obsession with young female suicides. Looking at her work, I am not ‘haunted’ by the reverie left behind of her blurred body, the long exposures of her obfuscation by chipped plaster and water tanks. All I am reminded of are the endless hours I’ve spent alone in the RISD darkrooms, confined in a solitary cubicle under dim, red light and the isolation of the printing process, a senseless suspension interrupted only by the timed bright light of the enlarger. The RISD Museum houses a print of hers, <i>Untitled (greenhouse)</i>, which depicts her crouched beneath the speckled shadows cast by the canopy of plants and the greenhouse ceiling. Her eyes are closed, and her hand is blurred in motion. When I first came upon it, I thought of a photo of mine taken in that same corridor of that same greenhouse, a portrait of a friend. They are not that different, albeit my friend looks more poised and far less comfortable in front of the mechanical gaze of the lens. Both photos carried a 4x5 aspect ratio, and I wondered whether Woodman captured herself with the same clunky monorail, struggling to adjust the stiff bellows.<br/>
          &emsp;&emsp;In her letters to Wendy MacNeil, Woodman’s cramped chicken-scratch hugs her postcard prints. She curved her letters, sometimes drawing strict lines through passages filled with wit and nonchalance, but also with the fearful anticipation that accompanies success and failure. Sometimes she mocked herself, other times the world around her. A shadow of doubt seemed to follow her. She lived in an era where written communication was not cheap like it is today. It was her words and not her image that gave her shape outside the frame.
        </p>

        <p>
          I wanted to formulate a methodology concerning how I viewed the photograph beyond what existed within the visual frame. It was clear that Woodman’s photographs were lacking to me in the absence of her correspondence between her and MacNeil. They were too easily exploited without written context, the act of viewing them too assuming and dubious on the part of the spectator. I became obsessed with not the images themselves, but rather the manners in which they could be seen to escape the physical confines of technicality. There had to be something in capturing an image that lay beyond the machinations of the camera, the stoichiometry of developing and printing. It seemed impertinent for the photograph to be viewed as the final product when it was a mere fragment of a continuum, especially when its legacy failed to carry the original intent under which it was created. The obvious solution was to photograph the entire continuum, or in the other words, turn towards film as a medium. However, videos structured themselves too easily around narrative, promoting a narrow range of consumption. Unable to be read, the intent of the photographer is often absent in the space of the narrative. As the viewer, you can pick up visual cues and historical context, but the uncertainty can never be erased.<br/>
          &emsp;&emsp;There is a photograph described by Barthes in Camera Lucida, known as the Winter Garden photograph, that he uses to inspect the personal interest a spectator holds in any given photograph. This photograph, of his mother as a child, is absent among the appendix of photographs Barthes chose to include in his work. Its significance was exclusive to an individual (Barthes). Can a photograph exist in the absence of the image? The photograph is a recreation of an image. If an image is a perceived moment in time (the visual scene that the photographer witnesses), then the photograph is the medium that allows the image to travel beyond the moment. We, the spectators, were not present when the image was captured through the lens of the camera. Instead, we are subjected to viewing the image in discontinuity, taken from its present and placed within ours. The image we are now viewing (defined as the photograph) is one that was imagined by the image-taker, the photographer. While we never get to see the original Winter Garden image or it’s translation, (transferring a photograph to print is an act of translation, albeit one with little information lost or changed), we are shown a new ‘photograph’ altogether. In the process of creating discourse surrounding the Winter Garden photograph, Barthes has described, and therefore depicted, an entirely new and reimagined photograph for the reader (spectator) that can exist in isolation from the original. I view Woodman’s correspondance with MacNeil in the same manner. It is a photograph stitched together from written moments separated temporally by years, and geographically by an ocean’s length. In it, I feel as if I can see Woodman more clearly than in any other photograph she has taken of herself.
        </p>

        <p>
          I spent over a year doing various exercises from The Photographer’s Playbook, several entries telling me to shoot more, think less, several more telling me to think more, shoot less. Other notable entries directed me to look at Diane Arbus, Francesca Woodman, to discard Berger for Fanon and read Barthes and interestingly, Borges and Emily Dickinson. That they would direct me to Borges, a master in crafting stories built upon words was perhaps indicative of everything I was unable to find within the photograph. The lesson that has stuck with me the longest was a lesson from Kota Ezawa: to make a photograph, and then when you are done, don’t take a picture of it. It would be my last lesson from the playbook and the last roll I have developed since then. A contact print filled with my grimacing face. It was nice, each time encountering a photograph I thought worth capturing, to let it escape. To turn the camera on myself and have the world observe me, observing it.
        </p>
        <img className = "text-image" src ={FrancescaWoodman}/>

      </div>
    );
  }
}
